default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  DATABASE_URL: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  DATABASE_URL: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: ezapp_production
  username: ezapp
  password: <%= ENV["POSTGRES_PASSWORD"] %>