default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  DATABASE_URL: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: ezapp_test

production:
  <<: *default
  database: ezapp_production
  username: ezapp
  password: <%= ENV["EZAPP_DATABASE_PASSWORD"] %>
