# Name of your application. Used to uniquely configure containers.
service: dummy

# Name of the container image.
image: thesiegmeister/dummy-kamal

# Deploy to these servers.
servers:
  web:
    - 128.199.151.24

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# Set ssl: false if using something like Cloudflare to terminate SSL (but keep host!).
proxy:
  ssl: true
  host: kamal.adsmart.ph
  app_port: 3000

# Credentials for your image host.
registry:
  username: thesiegmeister
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RACK_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

# Use a different ssh user than root
ssh:
  user: deploy

accessories:
  db:
    image: postgres:16.0
    host: 128.199.151.24
    env:
      clear:
        POSTGRES_USER: ezapp
        POSTGRES_DB: ezapp_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
